### ISSUE TITLE
Do you rewrite the replay parser based on manta or clarity? 

### ISSUE THREAD

**Issue by Moanrisy** [timkurvers/redota#101]
In the readme you mention
`ReDota is a heavily derived project and stands on the shoulders of giants, notably parsers by Dotabuff and Skadistats.

Special thanks to community members from OpenDota and ModDota who assisted in deciphering replay specifics.`

But when I read your code for the past few days, it look you rewrite it in js.

I currently trying to make something like reDota but run on terminal (tui) with go. Im just a bit lost about the dota2 replay structure or the anatomy.

**Comment by timkurvers** [comment]
Hi! Legit question, and it's not particularly clear from the README.

Most things under `src/lib/parser` are ported from Manta (Go) to JavaScript so it's usable directly in the browser without server involvement. The files have a comment on which source file they map to.

That said, there are some bits and pieces that come from Clarity (Java) instead, such as string table handling.
