### ISSUE TITLE
Git source crashes on ability "plus_high_five" but deployed version does not.

### ISSUE THREAD

**Issue by likwidoxigen** [timkurvers/redota#47]
Tried updating constants but that didn't work (it has it as high_five). 
So I went with adding a default value for when abilitiesByName fails out.
`this.definition = abilitiesByName[this.refname] || {dname: this.refname};`

Example match id: 6060924136

 I'd like to have my code match your implementation can you commit what you did?

**Comment by timkurvers** [comment]
Good catch! There's a few new Dota+ ablities that are not handled properly.

The reason it works on the deployed version is that abilities are not yet introduced there, there's no fix as of yet. Will fix and push shortly!

**Comment by timkurvers** [comment]
I've applied your fix in 7dd3c117c53258b3b244178c2fc899b3253755bf, thanks! In addition, 99d913f2f48d1c02e3cf7576f698c78ad1b3f4b6 prevents these Dota Plus abilities from showing as regular hero abilities.

Have also deployed the latest version / commit.

**Comment by likwidoxigen** [comment]
Awesome! Thanks, I've pulled these into my tree.
