### ISSUE TITLE
Support patch 7.32e

### ISSUE THREAD

**Issue by timkurvers** [timkurvers/redota#93]
Issues with patch 7.32e in ReDota:

- [x] Crash due to `GameTime_t` missing type definitions
- [x] Clock is currently incorrect (solution available in https://github.com/skadistats/clarity/issues/296)
- [x] Crash whenever new hero Muerta is referenced
- [x] Muerta lacks image resources

**Comment by Tsury** [comment]
Help Tim <3

**Comment by timkurvers** [comment]
Crash is prevented with 6f9d67ae86acad5691ea50191fe234d9c544c852, but the game clock is seemingly completely off.

Will have to investigate a bit more.

**Comment by Tsury** [comment]
I saw a [Clarity commit](https://github.com/skadistats/clarity/commit/f9bde0340d2056bcb3d9b47e7939ea5b695cbb0e) related to the issue, seems to be pretty much what you did. I wonder if it means that they suffer from this clock issue as well.

**Comment by timkurvers** [comment]
Yeah, that's definitely the same. I would imagine any parser that exposed `m_fGameTime` in any way (like Redota does) is gonna have this clock problem.

**Comment by Tsury** [comment]
Seems like `m_flGameStartTime` is still there, but yeah no sign of `m_fGameTime` or `GameTime_t` in any of the new replays. Could this be related to protobufs? Clarity also [updated those](https://github.com/skadistats/clarity-protobuf/commit/a09bbac3ffa889ebbfadfd786cc88141b12daff6).

**Comment by STRATZ-Ken** [comment]
Following, I think we could determine how many tick per second, we could just calculate based on the ticks in the replay.  I thought it was 30 ticks, but seems to not be the case. I think its very close to 30.

![image](https://user-images.githubusercontent.com/24981405/223537804-01d9250c-c4c3-4af0-b83d-5bc1f85116fe.png)


22841 / 30 = 761.366 seconds.  Which is incorrect.

22841 / 768.3334 = 29.72 ticks per second?

**Comment by Tsury** [comment]
Yeah I remember getting this number as well - I'll double check just in case.
Do note that you have to account for `m_bGamePaused` since ticks continue even when the game is paused.

**Comment by STRATZ-Ken** [comment]
Correct, but I think we may run into a problem during the pick stage.  As the first number comes once the game pre-loads.  So we won't know how long it took all players to load into the game successfully.

**Comment by Tsury** [comment]
Can maybe use `m_flPreGameStartTime` and count backwards. Depends on game mode - non turbo is 1:30 and turbo is 1:00.

**Comment by Tsury** [comment]
From my tests right now it's exactly 1/30, and previously `fGameTime` was sent every 2 ticks.

**Comment by timkurvers** [comment]
Tick interval is part of the `CSVCMsg_ServerInfo` message, but I am a bit unsure whether it's reliable.

**Comment by STRATZ-Ken** [comment]
I took these values (the last is the tick value it updated) and the first value is the time in game for `PreGameStartTime`

![image](https://user-images.githubusercontent.com/24981405/223549424-6abfc3b0-e42d-4d24-a0fa-f36bcc900eaa.png)


So for example : 878.500061 @ 26149 * 0.033333333 = 871.63 which is about 7 seconds off the correct number.

**Comment by timkurvers** [comment]
Bit of a busy day ahead, but hope to have this implemented (with backwards compatibility) either today or tomorrow.

**Comment by timkurvers** [comment]
Fixed in 4c5fd883107ada259d185033d67238b11a06cf9e.

Version 1.7.0, with these changes, available on the website now.
